name: "Chromatic"

on:
  push:
    branches:
      - main
    paths:
      - "packages/**/CHANGELOG.md" # with a pending release
  pull_request:
    branches:
      - main
    branches-ignore:
      - "renovate/**"
  workflow_dispatch:

jobs:
  chromatic-primitives:
    runs-on: ubuntu-latest
    timeout-minutes: 4

    defaults:
      run:
        working-directory: ./packages/primitives

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 22.14.0

      - name: Setup pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          workingDir: ./packages/primitives
          buildScriptName: "storybook:build"

  chromatic-forms:
    runs-on: ubuntu-latest
    timeout-minutes: 4

    defaults:
      run:
        working-directory: ./packages/forms

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 22.14.0

      - name: Setup pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN_FORMS }}
          workingDir: ./packages/forms
          buildScriptName: "storybook:build"
