name: Release (release-please)

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest

    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v4
        # these if statements ensure that a publication only occurs when
        # a new release is created:
        if: ${{ steps.release.outputs.release_created }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"
          registry-url: "https://registry.npmjs.org"
        if: ${{ steps.release.outputs.release_created }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10.6.3
        if: ${{ steps.release.outputs.release_created }}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        if: ${{ steps.release.outputs.release_created }}

      - name: Build package
        run: pnpm build
        if: ${{ steps.release.outputs.release_created }}

      - name: Publish to npm Registry
        run: pnpm publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        if: ${{ steps.release.outputs.release_created }}
